make new app type
thecodezone/dt-home pull request #111
Opened 2024-05-07 10:42 UTC by ancy2023

commite to the make new app type

2024-05-08 14:14 UTC, incraigulous requested changes

2024-05-08 14:14 UTC, incraigulous commented on resources/views/settings/edit.php
> -        <?php if ($existing_data['type'] === 'Web View') { ?>
Add this line back, but  change it to: 

```php
 <?php if ( $existing_data['type'] === 'Web View' || $existing_data['type'] === 'Link'  ) { ?>
 ```

2024-05-08 14:14 UTC, incraigulous commented on resources/views/web-view.php
> +$this->layout('layouts/web-view');
Your linter removes spaces around the function parameters (line 8 and 14), but there should be spaces according to WordPress CodeStyle. Please add them back.

2024-05-10 10:54 UTC, ancy2023 commented
I have completed the review changes and committed again

2024-05-10 14:08 UTC, incraigulous approved these changes

2024-05-10 14:15 UTC, merged