Remove Clean Up Test
thecodezone/dt-home pull request #169
Opened 2024-09-10 09:01 UTC by kodinkat

2024-09-10 22:56 UTC, incraigulous requested changes
I think we can remove the table drops from the cleanup method. I don't think we need them anymore. What do you think, @kodinkat?

2024-09-10 22:57 UTC, incraigulous requested changes
Remove the test ordering remove table drops from cleanup file.

2024-09-11 09:21 UTC, kodinkat commented
> I think we can remove the table drops from the cleanup method. I don't think we need them anymore. What do you think, @kodinkat?

Agreed. Ordering removed and reintroduced clean-up test and removed table drop statements.

2024-09-11 17:23 UTC, incraigulous approved these changes

2024-09-11 17:31 UTC, incraigulous approved these changes

2024-09-11 17:31 UTC, merged