Setting-app-testing
thecodezone/dt-home pull request #219
Opened 2024-10-14 13:28 UTC by Perumal605

2024-10-14 17:53 UTC, incraigulous requested changes

2024-10-14 17:53 UTC, incraigulous commented on tests/SettingAppTest.php
> +        $this->assertCount( 2, $setting_apps );
@Perumal605 , please loop though each $app and make sure it's slug exists in the database. You can use `->find()` for this, or search the $settings_apps array.

2024-10-14 17:53 UTC, incraigulous commented on tests/SettingAppTest.php
> +    public function it_save()
Rename to `it_saves`.

2024-10-14 17:53 UTC, incraigulous commented on tests/SettingAppTest.php
> +            $this->assertContains( $slug, $get_app_slugs );
Great!

2024-10-14 17:53 UTC, incraigulous commented on tests/SettingAppTest.php
> +    }
Please add the remaining methods that are inherited from `AppSource` and `Source`

2024-10-18 13:27 UTC, Perumal605 commented
@incraigulous I have pushed the latest updates here.

2024-10-21 17:03 UTC, merged